networks:
  loki:
  mqtt:
  api:

services:

  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    restart: always
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
      - "9003:9003"
    volumes:
      - ./questdb-data:/var/lib/questdb
    environment:
      QDB_PG_USER: admin
      QDB_PG_PASSWORD: quest
      QDB_HTTP_AUTHENTICATION: "true"
    networks:
      - mqtt
      - api
    healthcheck:
      test: ["CMD-SHELL", "echo", "</dev/tcp/localhost/9003"] // Tjekker om der er forbindelse til port 9003
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  fastapi:
    build:
      context: ./app
    container_name: fastapi
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    environment:
      QDB_HOST: questdb
      QDB_PORT: "8812"
      QDB_USER: admin
      QDB_PASSWORD: quest
      QDB_DB: qdb
    depends_on:
      questdb:
        condition: service_healthy
    networks:
      - api
      - mqtt
    healthcheck:
      test: ["CMD-SHELL", "echo", "</dev/tcp/http://localhost:8000/"] // Tjekker om der er forbindelse til port 8000
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 8s

