server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: mosquitto
    static_configs:
      - targets:
          - localhost
        labels:
          job: mosquitto
          __path__: /mosquitto/log/mosquitto.log

  - job_name: fastapi
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /app/logs/*.log

  - job_name: questdb
    static_configs:
      - targets:
          - localhost
        labels:
          job: questdb
          __path__: /var/lib/questdb/db/log/*.log
